<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '(Setting Changed)' => '',
  'Add Setting' => '',
  'Add Setting Group' => '',
  'Adding Setting' => '',
  'Adding setting group' => '',
  'Configure Settings' => '',
  'Count' => '',
  'Description' => '',
  'Editing Setting' => '',
  'Editing setting group' => '',
  'Group Unique Key' => '',
  'Key' => '',
  'No categories found.' => '',
  'Options' => '',
  'Setting Current Value' => '',
  'Setting Default Value' => '',
  'Setting Description' => '',
  'Setting Extra' => '',
  'Setting Group' => '',
  'Setting Key' => '',
  'Setting PHP Code' => '',
  'Setting Reverted.' => '',
  'Setting Title' => '',
  'Setting Type' => '',
  'Setting Unique Key' => '',
  'Setting Value' => '',
  'Setting added.' => '',
  'Setting deleted.' => '',
  'Setting edited.' => '',
  'Setting group added.' => '',
  'Setting group deleted.' => '',
  'Setting group updated.' => '',
  'Settings Categories' => '',
  'Settings Updated.' => '',
  'Title' => '',
  'Total Settings' => '',
  'View category settings' => '',
);
