<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '-- Choose Value --' => '-- 请选择 --',
  'Add setting to this group' => '添加设置到此组',
  'Adding Setting' => '添加设置',
  'Adding setting group' => '新建设置组',
  'Delete this group!' => '删除此组！',
  'Delete this setting!' => '删除此设置',
  'Edit this group' => '',
  'Edit this setting' => '',
  'Editing Setting' => '',
  'Editing setting group' => '',
  'Revert setting value to the default value.' => '',
  'Save' => '',
  'Settings' => '',
  'Submit' => '',
);
