<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  '(Setting Changed)' => '(已修改)',
  'Add Setting' => '添加设置项',
  'Add Setting Group' => '添加设置组',
  'Adding Setting' => '正在添加设置项',
  'Adding setting group' => '正在添加设置组',
  'Configure Settings' => '配置设置项 ',
  'Count' => '数量',
  'Description' => '描述',
  'Editing Setting' => '正在编辑设置项',
  'Editing setting group' => '正在编辑设置组',
  'Group Unique Key' => '组唯一键',
  'Key' => '键',
  'No categories found.' => '没有设置组',
  'Options' => '选项',
  'Setting Current Value' => '设置项当前值',
  'Setting Default Value' => '设置项默认值',
  'Setting Description' => '设置项描述',
  'Setting Extra' => '设置项扩展',
  'Setting Group' => '设置组',
  'Setting Key' => '设置项 key',
  'Setting PHP Code' => '设置项 PHP 代码',
  'Setting Reverted.' => '设置项',
  'Setting Title' => '设置项',
  'Setting Type' => '设置项类型',
  'Setting Unique Key' => '设置项唯一键',
  'Setting Value' => '设置值',
  'Setting added.' => '设置项已添加',
  'Setting deleted.' => '设置项已删除',
  'Setting edited.' => '设置项已修改',
  'Setting group added.' => '设置组已添加',
  'Setting group deleted.' => '设置组已删除',
  'Setting group updated.' => '设置组已更新',
  'Settings Categories' => '设置项分类',
  'Settings Updated.' => '设置项已更新',
  'Title' => '标题',
  'Total Settings' => '设置项总数',
  'View category settings' => '看设置分类',
);
