<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Alias' => '别名',
  'Article Date' => '日期',
  'Author' => '作者',
  'Category' => '分类',
  'Class Code' => '类别',
  'Content' => '内容',
  'Create Date' => '创建时间',
  'Delete {Article}' => '删除{Article}',
  'Description' => '描述',
  'Essential' => '',
  'File Path' => '文件路径',
  'Group' => '工作组',
  'Hash' => 'Hash码',
  'ID' => 'ID',
  'Image Path' => '图片路径',
  'Status' => '状态',
  'Tags' => '标签',
  'Title' => '标题',
  'Update Date' => '更新日期',
  'Update User' => '更新用户',
  'Views' => '查看次数',
  'Are you sure you want to delete this item?' => '您确定要删除吗？',
  'Create {Article}' => '添加{Article}',
  'Delete Article' => '删除文字',
  'ID' => 'ID',
  'List {Article}' => '{Article}列表',
  'Manage {Article}' => '管理{Article}',
  'Update {Article}' => '更新{Article}',
  'Blog'=>'博客',
  'Tutorials'=>'教程',
  'Document'=>'文档',
  'Handbook'=>'手册',
  'Settings'=>'配置',
  'Notice'=>'通知',
  'Manage {Articles}' => '管理{Articles}',
  'Attachment'=>'附件',
  'Update Article'=>'更新文章',
  'New Event'=>'新增',
  'Update Event'=>'更新',
  ''=>'',
);
